/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecommendedRouteImport } from './routes/recommended'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant.$threadId'
import { Route as SchemesIdRouteImport } from './routes/schemes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendedRoute = RecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssistantRoute,
} as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AssistantRoute,
} as any)
const SchemesIdRoute = SchemesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SchemesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/eligibility': typeof EligibilityRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/recommended': typeof RecommendedRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/assistant/': typeof AssistantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/eligibility': typeof EligibilityRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/recommended': typeof RecommendedRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/assistant': typeof AssistantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/eligibility': typeof EligibilityRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/recommended': typeof RecommendedRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/assistant/': typeof AssistantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/eligibility'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/recommended'
    | '/register'
    | '/saved'
    | '/schemes'
    | '/assistant/$threadId'
    | '/schemes/$id'
    | '/assistant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/eligibility'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/recommended'
    | '/register'
    | '/saved'
    | '/schemes'
    | '/assistant/$threadId'
    | '/schemes/$id'
    | '/assistant'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/eligibility'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/recommended'
    | '/register'
    | '/saved'
    | '/schemes'
    | '/assistant/$threadId'
    | '/schemes/$id'
    | '/assistant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EligibilityRoute: typeof EligibilityRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RecommendedRoute: typeof RecommendedRoute
  RegisterRoute: typeof RegisterRoute
  SavedRoute: typeof SavedRoute
  SchemesRoute: typeof SchemesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommended': {
      id: '/recommended'
      path: '/recommended'
      fullPath: '/recommended'
      preLoaderRoute: typeof RecommendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/schemes/$id': {
      id: '/schemes/$id'
      path: '/$id'
      fullPath: '/schemes/$id'
      preLoaderRoute: typeof SchemesIdRouteImport
      parentRoute: typeof SchemesRoute
    }
  }
}

interface AssistantRouteChildren {
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
}

const AssistantRouteChildren: AssistantRouteChildren = {
  AssistantThreadIdRoute: AssistantThreadIdRoute,
  AssistantIndexRoute: AssistantIndexRoute,
}

const AssistantRouteWithChildren = AssistantRoute._addFileChildren(
  AssistantRouteChildren,
)

interface SchemesRouteChildren {
  SchemesIdRoute: typeof SchemesIdRoute
}

const SchemesRouteChildren: SchemesRouteChildren = {
  SchemesIdRoute: SchemesIdRoute,
}

const SchemesRouteWithChildren =
  SchemesRoute._addFileChildren(SchemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EligibilityRoute: EligibilityRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RecommendedRoute: RecommendedRoute,
  RegisterRoute: RegisterRoute,
  SavedRoute: SavedRoute,
  SchemesRoute: SchemesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
